# Generated by Django 4.0.4 on 2022-06-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='plant',
            new_name='plant_name',
        ),
    ]
