# Generated by Django 4.0.4 on 2022-05-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scion_gardens', '0002_rename_reminders_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plantcollection',
            name='location',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
