# Generated by Django 4.0.4 on 2022-06-28 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scion_gardens', '0003_remove_reminder_plant_remove_reminder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcollection',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
