# Generated by Django 4.0.4 on 2022-05-23 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 23, 20, 12, 3, 279296, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 20, 12, 20, 860573, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
