# Generated by Django 4.0.4 on 2022-06-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scion_gardens', '0003_remove_reminder_plant_remove_reminder_user_and_more'),
        ('reminders', '0003_alter_reminder_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='plant',
        ),
        migrations.AddField(
            model_name='reminder',
            name='plant_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_plant', to='scion_gardens.plantcollection'),
        ),
    ]
